name: Push to the internet
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: get stuff
        uses: actions/checkout@v2
      - name: get creds
        run: aws sts get-caller-identity