name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn